name: 'Setup go-gitsemver'
description: 'Install the go-gitsemver CLI from GitHub Releases'
branding:
  icon: 'download'
  color: 'blue'

inputs:
  version:
    description: 'Version to install (e.g., v1.5.0). Use "latest" for the most recent release.'
    required: false
    default: 'latest'
  token:
    description: 'GitHub token for authenticated downloads (avoids rate limits).'
    required: false
    default: ''
  verify-checksum:
    description: 'Verify SHA-256 checksum of the downloaded binary.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Determine platform
      id: platform
      shell: bash
      run: |
        # Use runner context for reliable cross-platform detection
        RUNNER_OS="${{ runner.os }}"
        RUNNER_ARCH="${{ runner.arch }}"

        # Map runner.os to release asset names
        case "$RUNNER_OS" in
          Linux)   OS="linux" ;;
          macOS)   OS="darwin" ;;
          Windows) OS="windows" ;;
          *)       echo "::error::Unsupported OS: $RUNNER_OS"; exit 1 ;;
        esac

        # Map runner.arch to release asset names
        case "$RUNNER_ARCH" in
          X64)   ARCH="amd64" ;;
          ARM64) ARCH="arm64" ;;
          *)     echo "::error::Unsupported architecture: $RUNNER_ARCH"; exit 1 ;;
        esac

        # Build binary name
        if [ "$OS" = "windows" ]; then
          BINARY="go-gitsemver-${OS}-${ARCH}.exe"
        else
          BINARY="go-gitsemver-${OS}-${ARCH}"
        fi

        echo "os=$OS" >> "$GITHUB_OUTPUT"
        echo "arch=$ARCH" >> "$GITHUB_OUTPUT"
        echo "binary=$BINARY" >> "$GITHUB_OUTPUT"

    - name: Download go-gitsemver
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        BINARY="${{ steps.platform.outputs.binary }}"
        DOWNLOAD_DIR="${RUNNER_TEMP:-/tmp}/go-gitsemver-download"
        mkdir -p "$DOWNLOAD_DIR"

        if [ "$VERSION" = "latest" ]; then
          BASE_URL="https://github.com/MyCarrier-DevOps/go-gitsemver/releases/latest/download"
        else
          BASE_URL="https://github.com/MyCarrier-DevOps/go-gitsemver/releases/download/${VERSION}"
        fi

        CURL_ARGS=(-sL --fail --retry 3 --retry-delay 2)
        if [ -n "${{ inputs.token }}" ]; then
          CURL_ARGS+=(-H "Authorization: token ${{ inputs.token }}")
        fi

        echo "Downloading go-gitsemver from: ${BASE_URL}/${BINARY}"
        curl "${CURL_ARGS[@]}" "${BASE_URL}/${BINARY}" -o "${DOWNLOAD_DIR}/go-gitsemver" || {
          echo "::error::Failed to download go-gitsemver from ${BASE_URL}/${BINARY}"
          exit 1
        }

        # Checksum verification
        if [ "${{ inputs.verify-checksum }}" = "true" ]; then
          echo "Downloading checksums..."
          curl "${CURL_ARGS[@]}" "${BASE_URL}/checksums.txt" -o "${DOWNLOAD_DIR}/checksums.txt" || {
            echo "::error::Failed to download checksums.txt from ${BASE_URL}/checksums.txt"
            exit 1
          }

          EXPECTED=$(grep "${BINARY}" "${DOWNLOAD_DIR}/checksums.txt" | awk '{print $1}')
          if [ -z "$EXPECTED" ]; then
            echo "::error::No checksum found for ${BINARY} in checksums.txt"
            exit 1
          fi

          ACTUAL=$(shasum -a 256 "${DOWNLOAD_DIR}/go-gitsemver" | awk '{print $1}')
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "::error::Checksum mismatch for ${BINARY}"
            echo "::error::  Expected: $EXPECTED"
            echo "::error::  Actual:   $ACTUAL"
            exit 1
          fi
          echo "Checksum verified: $ACTUAL"
        fi

        chmod +x "${DOWNLOAD_DIR}/go-gitsemver"
        echo "download_dir=$DOWNLOAD_DIR" >> "$GITHUB_OUTPUT"

    - name: Install go-gitsemver
      id: download
      shell: bash
      run: |
        DOWNLOAD_DIR="${RUNNER_TEMP:-/tmp}/go-gitsemver-download"
        if [ "${{ steps.platform.outputs.os }}" = "windows" ]; then
          mkdir -p "$HOME/bin"
          mv "${DOWNLOAD_DIR}/go-gitsemver" "$HOME/bin/go-gitsemver.exe"
          echo "$HOME/bin" >> "$GITHUB_PATH"
        else
          sudo mv "${DOWNLOAD_DIR}/go-gitsemver" /usr/local/bin/
        fi
        rm -rf "$DOWNLOAD_DIR"

    - name: Verify installation
      shell: bash
      run: go-gitsemver version
