# yaml-language-server: $schema=https://raw.githubusercontent.com/MyCarrier-DevOps/go-gitsemver/main/go-gitsemver-schema.json
base-version: 1.0.0
tag-prefix: '[vV]'
mode: Mainline
mainline-increment: EachCommit
commit-date-format: yyyy-MM-dd
update-build-number: true

branches:
  main:
    regex: ^integration$
    mode: Mainline
    tag: ''
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: []
    is-source-branch-for: []
    is-release-branch: false
    is-mainline: true

  feature:
    regex: ^features?[/-](?<BranchName>.+)
    mode: Mainline
    tag: '{BranchName}'
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches:
      - main
      - feature
    is-source-branch-for: []
    is-release-branch: false
    is-mainline: false

  hotfix:
    regex: ^hotfix[/-](?<BranchName>.+)
    mode: Mainline
    tag: '{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    source-branches:
      - main
    is-source-branch-for: []
    is-release-branch: false
    is-mainline: false

  unknown:
    regex: .*
    mode: Mainline
    tag: '{BranchName}'
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches:
      - main
      - feature
    is-source-branch-for: []
    is-release-branch: false
    is-mainline: false